service: picture-2-text

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10

functions:
  ocr:
    handler: handler.ocr
    events:
      - http:
          path: ocr/
          method: post
